/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.gui;

import cl.model.Data;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author youkerplayer
 */
public class Mascota extends javax.swing.JFrame {
    private Data d;
    

    /**
     * Creates new form Mascota
     */
    public Mascota() {     
        try {
           initComponents();
           d = new Data();  
           vidaBar();
            setLocationRelativeTo(null);
            setTitle("Homunculo Virtual");
            
              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error de conexión: "+e,"Error",JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }   
    
    public class progreso implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            barVida.setValue(100);
            
//            if (n<100) {
//                n++;
//                jPVida.setValue(n);
//            }else{
//                timer.stop();
//                JOptionPane.showMessageDialog(null, "La vida ah llegado a cero");
//            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barVida = new javax.swing.JProgressBar();
        barHambrer = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGolepar = new javax.swing.JButton();
        btnAlimentar = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnDormir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barVida.setValue(100);
        jPanel1.add(barVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, 275, 23));

        barHambrer.setToolTipText("");
        jPanel1.add(barHambrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 29, 275, 22));

        jProgressBar3.setValue(100);
        jPanel1.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 57, 275, 24));

        jLabel1.setText("Vida:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 9, -1, -1));

        jLabel2.setText("Hambre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 37, -1, -1));

        jLabel3.setText("Entretención:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 67, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/materiales/render by annyz kawaii blog (36).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 99, 147, -1));

        btnGolepar.setText("Golpear");
        btnGolepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoleparActionPerformed(evt);
            }
        });
        jPanel1.add(btnGolepar, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 127, 77, -1));

        btnAlimentar.setText("Alimentar");
        btnAlimentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlimentarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlimentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 126, -1, -1));

        btnJugar.setText("Jugar");
        jPanel1.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 183, 77, -1));

        btnDormir.setText("Dormir");
        jPanel1.add(btnDormir, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 187, 77, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlimentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlimentarActionPerformed
        try {
            d.alimentarMascota(barVida.getValue());
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlimentarActionPerformed

    private void btnGoleparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoleparActionPerformed
        try {
        } catch (Exception e) {
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnGoleparActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mascota().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barHambrer;
    private javax.swing.JProgressBar barVida;
    private javax.swing.JButton btnAlimentar;
    private javax.swing.JButton btnDormir;
    private javax.swing.JButton btnGolepar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar3;
    // End of variables declaration//GEN-END:variables
    public void vidaBar() throws SQLException{
    d.vidaMascota(100);
    
    }

}

